trenndal_snowtricks:
    resource: "@TrenndalSnowtricksBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    path: /login_check

logout:
    path: /logout

app:
    resource: '@AppBundle/Controller/'
    type: annotation
