<?php

namespace Trenndal\SnowtricksBundle\Repository;

/**
 * EditTrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditTrickRepository extends \Doctrine\ORM\EntityRepository
{
}
